### ISSUE TITLE
Migrate endpoint v1/customer/current

### ISSUE THREAD

**Issue by af23me** [sebgroup/openbanking#11]
Hello everyone and @lgrkvst,

I just started to use API v2 and seems It impossible to get information about current customer under v2 API due missing scopes.

Do you have any information about plans migrate this endpoint under v2?

**Comment by lgrkvst** [comment]
Hi @af23me! Get in touch with our handsome colleagues in the Baltics – they'll know for sure: openbanking@seb.lt

=]
